# Generated by Django 5.1.1 on 2024-10-20 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_name',
            new_name='post_title',
        ),
    ]
